"""翻译服务。
负责中英双语文本字典、语言切换和页面翻译入口。"""

import streamlit as st


translations = {
    "zh": {
        "home_title": "首页",
        "home_summary": "欢迎使用电商数据分析平台，支持数据集内置查看与上传分析。",
        "platform_title": "电商数据分析平台",
        "platform_subtitle": "请从侧边栏选择模块。",
        "language_label": "语言",
        "english": "English",
        "chinese": "中文",
        "nav_group_data": "数据中心",
        "nav_group_analytics": "分析模块",
        "nav_group_ai": "AI助手",
        "nav_group_system": "系统信息",
        "dataset_center": "数据中心",
        "dataset_center_summary": "管理内置数据集和用户上传数据。",
        "builtins_header": "内置数据集",
        "upload_section": "上传数据",
        "upload_placeholder": "上传 CSV 或 XLSX 文件（支持 .csv, .xls, .xlsx）",
        "upload_success": "上传成功，已保存到会话。",
        "dataset_name": "数据集名称",
        "dataset_source": "数据来源",
        "rows": "行数",
        "columns": "列数",
        "preview": "数据预览",
        "quality_report": "数据质量报告",
        "missing_values": "缺失值数量",
        "dtypes": "数据类型",
        "online_retail_name": "Online Retail",
        "online_retail_source": "UCI Online Retail dataset",
        "online_retail_description": "包含 UCI 上的在线零售交易记录，字段包括发票号、商品编码、描述、数量、日期、单价、客户 ID、国家等。",
        "online_retail_ii_name": "Online Retail II",
        "online_retail_ii_source": "Kaggle / Online Retail II",
        "online_retail_ii_description": "Online Retail II 为更长时间窗的电商交易数据，包含类似字段（可能区分不同时间区间）。",
        
        "missing_rate": "缺失率",
        "duplicate_rows": "重复行数量",
        "duplicate_rate": "重复率",
        "numeric_columns": "数值列数量",
        "categorical_columns": "类别列数量",
        "datetime_columns": "日期列数量",
        "memory_usage": "内存占用 (bytes)",
        "quality_score": "数据质量评分",
        "preview_top_n": "前10行",
        "dtypes_table": "字段类型表",
        "field_descriptions": "字段说明（示例值）",
        "describe_stats": "统计摘要",
        "load_label": "加载",
        "upload_error": "上传文件读取失败。",
        "current_dataset_label": "当前数据集",
        "no_dataset_loaded": "当前未加载任何数据集。",
        "empty_file": "空文件，无法读取。",
        "duplicate_columns": "重复列名",
        "all_empty_columns": "全空列",
        "file_size": "文件大小 (bytes)",
        "sales_analysis": "销售分析",
        "sales_analysis_summary": "展示销售趋势与关键指标（占位）。",
        "kpi_revenue": "销售额",
        "kpi_orders": "订单数",
        "kpi_customers": "客户数",
        "kpi_aov": "客单价",

        "monthly_sales_trend": "月度销售趋势",
        "sales_by_country": "各国家销售额",
        "top_10_products": "销售额前10商品",
        "revenue_share": "销售额占比",

        "label_revenue": "销售额",
        "label_country": "国家",
        "label_orders": "订单数",
        "label_month": "月份",
        "label_product": "商品",

        "no_valid_dates_to_show_trend": "没有可用的日期展示趋势。",
        "no_sales_data_for_trend": "没有用于趋势的销售数据。",
        "unable_compute_monthly_trend": "无法计算月度销售趋势。",
        "monthly_trend_requires_fields": "月度趋势需要日期和销售额字段。",

        "no_country_sales_data": "没有国家销售数据。",
        "unable_compute_sales_by_country": "无法计算各国销售额。",
        "country_revenue_field_missing": "缺少国家或销售额字段，无法展示国家分布。",

        "no_product_sales_data": "没有商品销售数据。",
        "unable_compute_top_products": "无法计算热销商品。",
        "product_revenue_field_missing": "缺少商品或销售额字段，无法展示热销商品。",

        "no_data_for_revenue_share": "没有用于销售额占比的数据。",
        "unable_render_revenue_share_chart": "无法渲染销售额占比图表。",
        "not_enough_fields_revenue_share": "字段不足，无法展示销售额占比。",

        "not_available": "无",
        "customer_analysis": "客户分析",
        "customer_analysis_summary": "客户画像与分群分析（占位）。",

        "kpi_total_customers": "总客户数",
        "kpi_active_customers": "活跃客户数",
        "kpi_avg_spend_per_customer": "人均消费金额",
        "kpi_avg_orders_per_customer": "人均订单数",

        "top_customers": "客户排行榜",
        "column_customer_id": "客户ID",
        "column_orders": "订单数",
        "column_revenue": "销售额",

        "rfm_analysis": "RFM 分析",
        "rfm_segments": "客户分层",
        "label_count": "数量",
        "segment_high_value": "高价值客户",
        "segment_loyal": "忠诚客户",
        "segment_normal": "普通客户",
        "segment_at_risk": "流失风险客户",

        "customer_value_distribution": "客户价值分布",
        "customer_revenue_distribution": "客户消费金额分布图",
        "customer_orders_distribution": "客户订单数分布图",

        "no_customers_data": "没有客户数据或缺少 CustomerID/销售额字段。",
        "no_rfm_data": "无法计算 RFM：缺少必要字段。",
        "unable_compute_rfm": "无法计算 RFM 分层。",
        "not_enough_rfm_fields": "RFM 分析需要 CustomerID、日期和销售额字段。",
        "top10_high_value_customers": "Top10高价值客户",
        "customer_segment_distribution": "客户价值等级分布",
        "customer_value_matrix": "客户价值矩阵",
        "customer_behavior_heatmap": "客户行为热力图",

        "seg_important_value": "重要价值客户",
        "seg_important_retention": "重要保持客户",
        "seg_important_develop": "重要发展客户",
        "seg_general_value": "一般价值客户",
        "seg_at_risk": "流失预警客户",

        "label_frequency": "订单数",
        "label_monetary": "消费金额",
        "label_customer_id": "客户ID",
        "label_segment": "客户等级",
        "label_frequency_bins": "订单频次区间",
        "label_monetary_bins": "消费金额区间",
        "product_analysis": "产品分析",
        "product_analysis_summary": "产品绩效与热销商品概览（占位）。",
        "market_basket_analysis": "市场篮子分析",
        "market_basket_analysis_summary": "关联规则与共购分析（占位）。",
        "forecast_analysis": "预测分析",
        "forecast_analysis_summary": "时间序列预测与趋势预估（占位）。",
        "ai_assistant": "AI 助手",
        "ai_assistant_summary": "基于 AI 的分析问答助手（占位）。",
        "about": "关于",
        "about_summary": "项目说明、数据来源与课程对齐说明。",

        "home_dashboard_title": "电商零售智能分析平台",
        "home_dashboard_subtitle": "基于 Online Retail 数据集的商业智能分析系统",
        "home_dataset_missing_hint": "当前未加载数据集。请先进入数据中心加载内置数据集或上传数据。",
        "home_kpi_total_sales": "总销售额",
        "home_kpi_total_orders": "总订单数",
        "home_kpi_customer_count": "客户数量",
        "home_kpi_product_count": "产品数量",
        "home_feature_nav": "功能导航",
        "home_nav_dataset_title": "数据中心",
        "home_nav_dataset_desc": "加载内置数据集、上传文件并查看数据质量。",
        "home_nav_sales_title": "销售分析",
        "home_nav_sales_desc": "查看销售趋势、地区表现和收入结构。",
        "home_nav_customer_title": "客户分析",
        "home_nav_customer_desc": "分析客户价值、RFM分层和客户贡献。",
        "home_nav_product_title": "产品分析",
        "home_nav_product_desc": "洞察产品排行、趋势和销售贡献。",
        "home_nav_basket_title": "市场篮子分析",
        "home_nav_basket_desc": "发现高频商品组合和关联规则。",
        "home_nav_forecast_title": "预测分析",
        "home_nav_forecast_desc": "预测未来销售趋势并比较模型表现。",
        "home_nav_ai_title": "AI助手",
        "home_nav_ai_desc": "基于当前数据集进行规则分析问答。",
        "home_enter_module": "进入模块",
        "home_project_highlights": "项目亮点",
        "home_highlight_rfm": "RFM客户分层",
        "home_highlight_basket": "市场篮子分析",
        "home_highlight_forecast": "销售预测",
        "home_highlight_ai": "AI数据助手",
        "home_dataset_info": "数据集信息",
        "home_dataset_info_title": "Online Retail Dataset",
        "home_dataset_info_desc": "包含在线零售交易记录，可用于销售、客户、产品、商品组合和预测分析。",
        "dataset_upload_title": "拖拽文件到此处或点击上传",
        "dataset_file_info": "文件信息",
        "dataset_data_size": "数据量",

        "ai_data_assistant_title": "AI 数据分析助手",
        "ai_data_assistant_intro": "基于当前数据集自动生成产品、客户、销售趋势和商品组合分析。",
        "ai_no_dataset_hint": "当前未加载数据集。请先在 Dataset Center 加载或上传数据。",
        "ai_kpi_dataset_name": "数据集名称",
        "ai_kpi_orders": "订单数",
        "ai_kpi_customers": "客户数",
        "ai_kpi_revenue": "销售额",
        "ai_quick_questions": "快捷问题",
        "ai_quick_top_product": "销售额最高的产品是什么？",
        "ai_quick_customer_contribution": "哪类客户贡献最大？",
        "ai_quick_recent_trend": "最近销售趋势如何？",
        "ai_quick_bundles": "哪些商品适合捆绑销售？",
        "ai_quick_advice": "给出经营建议",
        "ai_chat_input_placeholder": "请输入你的数据分析问题",
        "ai_chat_history_title": "分析问答记录",
        "ai_current_dataset": "当前数据集",
        "ai_no_product_field": "暂未识别到产品字段，无法判断销售额最高的产品。",
        "ai_no_product_records": "当前数据中没有可用于产品销售分析的记录。",
        "ai_top_product_answer": "**销售额最高的产品是：**\n\n- 产品名称：`{product}`\n- 销售额：**{revenue}**\n- 销量：**{quantity}**\n- 销售贡献占比：**{share}**",
        "ai_no_customer_field": "暂未识别到客户字段，无法进行客户贡献分层。",
        "ai_no_customer_records": "当前数据中没有可用于客户贡献分析的记录。",
        "ai_customer_contribution_answer": "**贡献最大的客户类型：高价值客户（销售额排名前 20%）**\n\n- 高价值客户数量：**{high_value_count}**\n- 贡献销售额：**{contribution}**\n- 销售贡献占比：**{share}**\n- 单个贡献最高客户：`{top_customer}`，销售额 **{top_customer_revenue}**\n\n建议优先围绕这类客户做复购、会员权益和精准营销。",
        "ai_no_date_field": "暂未识别到日期字段，无法分析最近销售趋势。",
        "ai_invalid_date_field": "日期字段无法解析为有效日期，暂时无法分析最近销售趋势。",
        "ai_not_enough_months": "月度销售数据不足，至少需要两个月的数据才能判断趋势。",
        "ai_recent_trend_header": "**最近销售趋势：**",
        "ai_recent_trend_last_sales": "- 最近一个月销售额：**{revenue}**",
        "ai_recent_trend_growth": "- 环比变化：**{growth}**",
        "ai_recent_trend_direction": "- 趋势判断：**{direction}**",
        "ai_recent_trend_last_three": "最近 3 个月销售额：",
        "ai_recent_trend_month_line": "- {month}：{revenue}",
        "ai_trend_up": "上升",
        "ai_trend_down": "下降",
        "ai_trend_flat": "基本平稳",
        "ai_no_basket_fields": "需要同时识别到商品字段和订单字段，才能分析适合捆绑销售的商品组合。",
        "ai_no_bundle_records": "当前订单中没有找到稳定的同购商品组合。",
        "ai_bundle_answer_header": "**适合优先尝试捆绑销售的商品组合：**",
        "ai_bundle_answer_item": "{index}. `{item_a}` + `{item_b}`：共同出现在 **{count}** 个订单中",
        "ai_bundle_answer_tip": "建议优先将这些组合用于套餐推荐、购物车加购提示或满减活动。",
        "ai_advice_answer": "**经营建议：**\n\n1. **强化头部产品运营**：\n{top_product}\n\n2. **关注近期趋势变化**：\n{trend}\n\n3. **提升高价值客户复购**：\n{customer}\n\n4. **开展捆绑销售测试**：\n{bundles}",
        "ai_overview_answer": "我可以基于当前数据集回答产品、客户、趋势和商品组合问题。\n\n- 数据集：`{dataset}`\n- 订单数：**{orders}**\n- 客户数：**{customers}**\n- 销售额：**{revenue}**\n\n你可以点击上方快捷问题，或直接输入类似“{example_question}”的问题。",
        "ai_model_config_title": "模型参数配置",
        "ai_model_config_desc": "预留大模型接口配置区域，当前页面仍使用本地规则分析生成回答。",
        "ai_provider_label": "服务商",
        "ai_api_key_label": "API Key",
        "ai_api_key_placeholder": "请输入 API Key",
        "ai_model_name_label": "Model Name",
        "ai_temperature_label": "Temperature",
        "ai_frontend_only_hint": "当前优先使用千问 API；若未设置 QIANWEN_API_KEY，将使用本地规则分析回答。",
        "ai_qwen_env_label": "API Key 来源：环境变量 QIANWEN_API_KEY 或 Streamlit Secrets",
        "ai_qwen_ready": "已检测到 QIANWEN_API_KEY，Qwen 将用于生成回答。",
        "ai_qwen_missing_key": "未检测到 QIANWEN_API_KEY，将使用本地规则分析回答。",
        "ai_qwen_error": "Qwen API 调用失败，以下为本地规则分析结果：\n\n{error}\n\n{fallback}",

        "about_page_title": "关于项目",
        "about_page_caption": "电商零售智能分析平台",
        "about_system_intro_title": "系统简介",
        "about_system_intro_body": "<p><strong>电商零售智能分析平台</strong> 面向电商零售交易数据，提供从数据接入、业务分析、客户分层、产品洞察、关联规则、销售预测到 AI 辅助决策的一体化分析体验。</p>",
        "about_modules_title": "功能模块",
        "about_module_dataset_title": "数据中心",
        "about_module_dataset_desc": "数据加载、预览、质量概览",
        "about_module_sales_title": "销售分析",
        "about_module_sales_desc": "销售趋势、地区表现、收入结构",
        "about_module_customer_title": "客户分析",
        "about_module_customer_desc": "RFM 分层、客户价值、贡献分析",
        "about_module_product_title": "产品分析",
        "about_module_product_desc": "产品排行、趋势、贡献度",
        "about_module_basket_title": "市场篮子分析",
        "about_module_basket_desc": "高频组合、关联规则、组合贡献",
        "about_module_forecast_title": "预测分析",
        "about_module_forecast_desc": "月度销售预测与业务解读",
        "about_module_ai_title": "AI助手",
        "about_module_ai_desc": "基于数据的规则分析问答",
        "about_tech_stack_title": "技术栈",
        "about_tech_python": "Python",
        "about_tech_pandas": "Pandas",
        "about_tech_numpy": "NumPy",
        "about_tech_plotly": "Plotly",
        "about_tech_streamlit": "Streamlit",
        "about_tech_sklearn": "Scikit-learn",
        "about_dataset_title": "数据集说明",
        "about_dataset_body": "<p><strong>Online Retail Dataset</strong></p><p>包含在线零售交易记录，常见字段包括订单编号、商品名称、数量、订单日期、单价、客户 ID 和国家/地区等，可用于销售、客户、产品和篮子分析。</p>",
        "about_features_title": "项目特色",
        "about_feature_sales": "销售分析",
        "about_feature_rfm": "RFM客户分层",
        "about_feature_product": "产品分析",
        "about_feature_basket": "市场篮子分析",
        "about_feature_forecast": "销售预测",
        "about_feature_ai": "AI辅助决策",
        "about_author_title": "作者信息",
        "about_author_body": "<p><strong>姓名：</strong>陈怡诺</p><p><strong>学号：</strong>2025200679</p>",
        "about_architecture_title": "系统架构图",
        "about_arch_data_title": "数据接入",
        "about_arch_data_desc": "内置数据集、CSV 和 Excel 上传。",
        "about_arch_engine_title": "分析引擎",
        "about_arch_engine_desc": "Pandas、Scikit-Learn 与规则分析。",
        "about_arch_visual_title": "可视化层",
        "about_arch_visual_desc": "Streamlit 页面与 Plotly 图表。",
        "about_arch_decision_title": "决策输出",
        "about_arch_decision_desc": "指标、趋势、分层、预测和 AI 辅助建议。",
        "page_not_implemented": "页面未实现 render() 接口。",
        "page_load_error": "无法加载页面",
    },
    "en": {
        "home_title": "Home",
        "home_summary": "Welcome to the e-commerce data analysis platform with built-in datasets and upload support.",
        "platform_title": "E-Commerce Data Platform",
        "platform_subtitle": "Please choose a module from the sidebar.",
        "language_label": "Language",
        "english": "English",
        "chinese": "中文",
        "nav_group_data": "DATA",
        "nav_group_analytics": "ANALYTICS",
        "nav_group_ai": "AI",
        "nav_group_system": "SYSTEM",
        "dataset_center": "Dataset Center",
        "dataset_center_summary": "Manage built-in datasets and user uploads.",
        "builtins_header": "Built-in Datasets",
        "upload_section": "Upload Dataset",
        "upload_placeholder": "Upload CSV or XLSX file (supports .csv, .xls, .xlsx)",
        "upload_success": "Upload successful and saved to session.",
        "dataset_name": "Dataset Name",
        "dataset_source": "Source",
        "rows": "Rows",
        "columns": "Columns",
        "preview": "Preview",
        "quality_report": "Data Quality Report",
        "missing_values": "Missing values",
        "dtypes": "Data types",
        "online_retail_name": "Online Retail",
        "online_retail_source": "UCI Online Retail dataset",
        "online_retail_description": "Contains online retail transactions from UCI; fields include InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country.",
        "online_retail_ii_name": "Online Retail II",
        "online_retail_ii_source": "Kaggle / Online Retail II",
        "online_retail_ii_description": "Online Retail II is a longer time-window e-commerce transactions dataset with similar fields.",
        
        "missing_rate": "Missing rate",
        "duplicate_rows": "Duplicate rows",
        "duplicate_rate": "Duplicate rate",
        "numeric_columns": "Numeric columns",
        "categorical_columns": "Categorical columns",
        "datetime_columns": "Datetime columns",
        "memory_usage": "Memory usage (bytes)",
        "quality_score": "Quality score",
        "preview_top_n": "Top 10 rows",
        "dtypes_table": "Column types",
        "field_descriptions": "Field descriptions (sample values)",
        "describe_stats": "Statistical summary",
        "load_label": "Load",
        "upload_error": "Failed to read uploaded file.",
        "current_dataset_label": "Current dataset",
        "no_dataset_loaded": "No dataset loaded.",
        "empty_file": "Empty file, cannot read.",
        "duplicate_columns": "Duplicate column names",
        "all_empty_columns": "All-empty columns",
        "file_size": "File size (bytes)",
        "sales_analysis": "Sales Analysis",
        "sales_analysis_summary": "Display sales trends and key metrics (placeholder).",
        "kpi_revenue": "Revenue",
        "kpi_orders": "Orders",
        "kpi_customers": "Customers",
        "kpi_aov": "AOV",

        "monthly_sales_trend": "Monthly Sales Trend",
        "sales_by_country": "Sales by Country",
        "top_10_products": "Top 10 Products",
        "revenue_share": "Revenue Share",

        "label_revenue": "Revenue",
        "label_country": "Country",
        "label_month": "Month",
        "label_product": "Products",

        "no_valid_dates_to_show_trend": "No valid dates to show trend.",
        "no_sales_data_for_trend": "No sales data for trend.",
        "unable_compute_monthly_trend": "Unable to compute monthly sales trend.",
        "monthly_trend_requires_fields": "Monthly trend requires date and revenue fields.",

        "no_country_sales_data": "No country sales data.",
        "unable_compute_sales_by_country": "Unable to compute sales by country.",
        "country_revenue_field_missing": "Country or revenue field missing; cannot show country breakdown.",

        "no_product_sales_data": "No product sales data.",
        "unable_compute_top_products": "Unable to compute top products.",
        "product_revenue_field_missing": "Product or revenue field missing; cannot show top products.",

        "no_data_for_revenue_share": "No data for revenue share.",
        "unable_render_revenue_share_chart": "Unable to render revenue share chart.",
        "not_enough_fields_revenue_share": "Not enough fields to render revenue share.",

        "not_available": "N/A",
        "customer_analysis": "Customer Analysis",
        "customer_analysis_summary": "Customer profiling and segmentation (placeholder).",

        "kpi_total_customers": "Total Customers",
        "kpi_active_customers": "Active Customers",
        "kpi_avg_spend_per_customer": "Avg Spend per Customer",
        "kpi_avg_orders_per_customer": "Avg Orders per Customer",

        "top_customers": "Top Customers",
        "column_customer_id": "CustomerID",
        "column_orders": "Orders",
        "column_revenue": "Revenue",
        "label_orders": "Orders",

        "rfm_analysis": "RFM Analysis",
        "rfm_segments": "RFM Segments",
        "label_count": "Count",
        "segment_high_value": "High Value",
        "segment_loyal": "Loyal",
        "segment_normal": "Normal",
        "segment_at_risk": "At-risk",

        "customer_value_distribution": "Customer Value Distribution",
        "customer_revenue_distribution": "Customer Revenue Distribution",
        "customer_orders_distribution": "Customer Orders Distribution",

        "no_customers_data": "No customers data or missing CustomerID/revenue fields.",
        "no_rfm_data": "Unable to compute RFM: missing required fields.",
        "unable_compute_rfm": "Unable to compute RFM segmentation.",
        "not_enough_rfm_fields": "RFM analysis requires CustomerID, date and revenue fields.",
        "top10_high_value_customers": "Top 10 High Value Customers",
        "customer_segment_distribution": "Customer Segment Distribution",
        "customer_value_matrix": "Customer Value Matrix",
        "customer_behavior_heatmap": "Customer Behavior Heatmap",

        "seg_important_value": "Important Value Customers",
        "seg_important_retention": "Important Retention",
        "seg_important_develop": "Important Development",
        "seg_general_value": "General Value",
        "seg_at_risk": "At-risk",

        "label_frequency": "Orders",
        "label_monetary": "Monetary",
        "label_customer_id": "CustomerID",
        "label_segment": "Segment",
        "label_frequency_bins": "Orders Frequency Bins",
        "label_monetary_bins": "Monetary Bins",
        "product_analysis": "Product Analysis",
        "product_analysis_summary": "Product performance and top-sellers overview (placeholder).",
        "market_basket_analysis": "Market Basket Analysis",
        "market_basket_analysis_summary": "Association rules and co-purchase analysis (placeholder).",
        "forecast_analysis": "Forecast Analysis",
        "forecast_analysis_summary": "Time-series forecasting and trend estimation (placeholder).",
        "ai_assistant": "AI Assistant",
        "ai_assistant_summary": "AI-powered Q&A assistant for analysis (placeholder).",
        "about": "About",
        "about_summary": "Project description, data sources and course alignment notes.",

        "home_dashboard_title": "E-Commerce Retail Intelligence Platform",
        "home_dashboard_subtitle": "Business Intelligence Analytics System Based on Online Retail Dataset",
        "home_dataset_missing_hint": "No dataset is currently loaded. Please go to Dataset Center to load a built-in dataset or upload data.",
        "home_kpi_total_sales": "Total Revenue",
        "home_kpi_total_orders": "Total Orders",
        "home_kpi_customer_count": "Customers",
        "home_kpi_product_count": "Products",
        "home_feature_nav": "Module Navigation",
        "home_nav_dataset_title": "Dataset Center",
        "home_nav_dataset_desc": "Load built-in datasets, upload files, and review data quality.",
        "home_nav_sales_title": "Sales Analysis",
        "home_nav_sales_desc": "Review sales trends, regional performance, and revenue structure.",
        "home_nav_customer_title": "Customer Analysis",
        "home_nav_customer_desc": "Analyze customer value, RFM segmentation, and contribution.",
        "home_nav_product_title": "Product Analysis",
        "home_nav_product_desc": "Explore product rankings, trends, and sales contribution.",
        "home_nav_basket_title": "Market Basket Analysis",
        "home_nav_basket_desc": "Discover frequent itemsets and association rules.",
        "home_nav_forecast_title": "Forecast Analysis",
        "home_nav_forecast_desc": "Forecast future sales trends and compare model behavior.",
        "home_nav_ai_title": "AI Assistant",
        "home_nav_ai_desc": "Ask rule-based analysis questions using the current dataset.",
        "home_enter_module": "Open Module",
        "home_project_highlights": "Project Highlights",
        "home_highlight_rfm": "RFM Customer Segmentation",
        "home_highlight_basket": "Market Basket Analysis",
        "home_highlight_forecast": "Sales Forecasting",
        "home_highlight_ai": "AI Data Assistant",
        "home_dataset_info": "Dataset Information",
        "home_dataset_info_title": "Online Retail Dataset",
        "home_dataset_info_desc": "Contains online retail transaction records for sales, customer, product, basket, and forecasting analysis.",
        "dataset_upload_title": "Drag and drop files here or click to upload",
        "dataset_file_info": "File Information",
        "dataset_data_size": "Data Size",

        "ai_data_assistant_title": "AI Data Analysis Assistant",
        "ai_data_assistant_intro": "Automatically generate product, customer, sales trend, and basket insights from the current dataset.",
        "ai_no_dataset_hint": "No dataset is currently loaded. Please load or upload data in Dataset Center first.",
        "ai_kpi_dataset_name": "Dataset Name",
        "ai_kpi_orders": "Orders",
        "ai_kpi_customers": "Customers",
        "ai_kpi_revenue": "Revenue",
        "ai_quick_questions": "Quick Questions",
        "ai_quick_top_product": "What is the highest-revenue product?",
        "ai_quick_customer_contribution": "Which customer group contributes the most?",
        "ai_quick_recent_trend": "How is the recent sales trend?",
        "ai_quick_bundles": "Which items are suitable for bundle sales?",
        "ai_quick_advice": "Give business recommendations",
        "ai_chat_input_placeholder": "Enter your data analysis question",
        "ai_chat_history_title": "Analysis Q&A History",
        "ai_current_dataset": "Current Dataset",
        "ai_no_product_field": "No product field was detected, so the highest-revenue product cannot be identified.",
        "ai_no_product_records": "There are no records available for product sales analysis in the current dataset.",
        "ai_top_product_answer": "**The highest-revenue product is:**\n\n- Product Name: `{product}`\n- Revenue: **{revenue}**\n- Quantity Sold: **{quantity}**\n- Sales Contribution Share: **{share}**",
        "ai_no_customer_field": "No customer field was detected, so customer contribution segmentation cannot be performed.",
        "ai_no_customer_records": "There are no records available for customer contribution analysis in the current dataset.",
        "ai_customer_contribution_answer": "**The largest contributing customer group is: high-value customers (top 20% by revenue)**\n\n- High-value customer count: **{high_value_count}**\n- Contributed revenue: **{contribution}**\n- Sales contribution share: **{share}**\n- Top individual customer: `{top_customer}`, revenue **{top_customer_revenue}**\n\nRecommendation: prioritize repeat purchase programs, membership benefits, and targeted marketing for this group.",
        "ai_no_date_field": "No date field was detected, so recent sales trends cannot be analyzed.",
        "ai_invalid_date_field": "The date field cannot be parsed into valid dates, so recent sales trends cannot be analyzed.",
        "ai_not_enough_months": "Monthly sales data is insufficient; at least two months are required to judge the trend.",
        "ai_recent_trend_header": "**Recent Sales Trend:**",
        "ai_recent_trend_last_sales": "- Latest month revenue: **{revenue}**",
        "ai_recent_trend_growth": "- Month-over-month change: **{growth}**",
        "ai_recent_trend_direction": "- Trend judgment: **{direction}**",
        "ai_recent_trend_last_three": "Revenue in the last 3 months:",
        "ai_recent_trend_month_line": "- {month}: {revenue}",
        "ai_trend_up": "upward",
        "ai_trend_down": "downward",
        "ai_trend_flat": "mostly stable",
        "ai_no_basket_fields": "Both product and order fields are required to analyze suitable bundle-sales item combinations.",
        "ai_no_bundle_records": "No stable co-purchased item combinations were found in the current orders.",
        "ai_bundle_answer_header": "**Item combinations worth testing first for bundle sales:**",
        "ai_bundle_answer_item": "{index}. `{item_a}` + `{item_b}`: appeared together in **{count}** orders",
        "ai_bundle_answer_tip": "Recommendation: use these combinations for bundle recommendations, cart add-on prompts, or threshold discount campaigns.",
        "ai_advice_answer": "**Business Recommendations:**\n\n1. **Strengthen operations for leading products:**\n{top_product}\n\n2. **Monitor recent trend changes:**\n{trend}\n\n3. **Increase repeat purchases from high-value customers:**\n{customer}\n\n4. **Test bundle sales:**\n{bundles}",
        "ai_overview_answer": "I can answer product, customer, trend, and item-combination questions based on the current dataset.\n\n- Dataset: `{dataset}`\n- Orders: **{orders}**\n- Customers: **{customers}**\n- Revenue: **{revenue}**\n\nYou can click a quick question above or type a question such as \"{example_question}\".",
        "ai_model_config_title": "Model Configuration",
        "ai_model_config_desc": "Reserved LLM API configuration area. The page still uses local rule-based analysis.",
        "ai_provider_label": "Provider",
        "ai_api_key_label": "API Key",
        "ai_api_key_placeholder": "Enter API Key",
        "ai_model_name_label": "Model Name",
        "ai_temperature_label": "Temperature",
        "ai_frontend_only_hint": "Qwen API is used when available. If QIANWEN_API_KEY is not set, local rule-based analysis is used.",
        "ai_qwen_env_label": "API Key source: QIANWEN_API_KEY environment variable or Streamlit Secrets",
        "ai_qwen_ready": "QIANWEN_API_KEY detected. Qwen will be used to generate answers.",
        "ai_qwen_missing_key": "QIANWEN_API_KEY was not detected. Local rule-based analysis will be used.",
        "ai_qwen_error": "Qwen API call failed. The local rule-based answer is shown below:\n\n{error}\n\n{fallback}",

        "about_page_title": "About",
        "about_page_caption": "E-Commerce Retail Intelligence Platform",
        "about_system_intro_title": "System Overview",
        "about_system_intro_body": "<p><strong>E-Commerce Retail Intelligence Platform</strong> is built for e-commerce retail transaction data, providing an integrated analytics experience from data intake and business analysis to customer segmentation, product insights, association rules, sales forecasting, and AI-assisted decision-making.</p>",
        "about_modules_title": "Functional Modules",
        "about_module_dataset_title": "Dataset Center",
        "about_module_dataset_desc": "Data loading, preview, and quality overview",
        "about_module_sales_title": "Sales Analysis",
        "about_module_sales_desc": "Sales trends, regional performance, and revenue structure",
        "about_module_customer_title": "Customer Analysis",
        "about_module_customer_desc": "RFM segmentation, customer value, and contribution analysis",
        "about_module_product_title": "Product Analysis",
        "about_module_product_desc": "Product rankings, trends, and contribution",
        "about_module_basket_title": "Market Basket Analysis",
        "about_module_basket_desc": "Frequent itemsets, association rules, and bundle contribution",
        "about_module_forecast_title": "Forecast Analysis",
        "about_module_forecast_desc": "Monthly sales forecasting and business interpretation",
        "about_module_ai_title": "AI Assistant",
        "about_module_ai_desc": "Rule-based data analysis Q&A",
        "about_tech_stack_title": "Tech Stack",
        "about_tech_python": "Python",
        "about_tech_pandas": "Pandas",
        "about_tech_numpy": "NumPy",
        "about_tech_plotly": "Plotly",
        "about_tech_streamlit": "Streamlit",
        "about_tech_sklearn": "Scikit-learn",
        "about_dataset_title": "Dataset Description",
        "about_dataset_body": "<p><strong>Online Retail Dataset</strong></p><p>Contains online retail transaction records. Common fields include order number, product name, quantity, order date, unit price, customer ID, and country/region, supporting sales, customer, product, and basket analysis.</p>",
        "about_features_title": "Project Features",
        "about_feature_sales": "Sales Analysis",
        "about_feature_rfm": "RFM Customer Segmentation",
        "about_feature_product": "Product Analysis",
        "about_feature_basket": "Market Basket Analysis",
        "about_feature_forecast": "Sales Forecasting",
        "about_feature_ai": "AI-assisted Decisions",
        "about_author_title": "Author Information",
        "about_author_body": "<p><strong>Name:</strong> Chen Yinuo</p><p><strong>Student ID:</strong> 2025200679</p>",
        "about_architecture_title": "System Architecture",
        "about_arch_data_title": "Data Intake",
        "about_arch_data_desc": "Built-in datasets, CSV, and Excel uploads.",
        "about_arch_engine_title": "Analytics Engine",
        "about_arch_engine_desc": "Pandas, Scikit-Learn, and rule-based analysis.",
        "about_arch_visual_title": "Visualization Layer",
        "about_arch_visual_desc": "Streamlit pages and Plotly charts.",
        "about_arch_decision_title": "Decision Output",
        "about_arch_decision_desc": "KPIs, trends, segments, forecasts, and AI-assisted advice.",
        "page_not_implemented": "Page does not implement render() interface.",
        "page_load_error": "Failed to load page",
    },
}


class Translator:
    def __init__(self, language=None):
        if "language" not in st.session_state:
            st.session_state.language = "en"
        self.language = language or st.session_state.language

    def t(self, key):
        return translations.get(self.language, {}).get(key, key)

    def set_language(self, language):
        st.session_state.language = language
        self.language = language


def t(key):
    translator = Translator()
    return translator.t(key)
